### ISSUE TITLE
dnsmasq missing problem...

### ISSUE THREAD

**Issue by D33M0N** [pi-hole/FTL#717]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
libvirtd does start without crying about dnsmasq missing and I can create VM's in virt-manager.
And if pi-hole-ftl does replace and provide dnsmasq as it claims, then it should mimic it better and actually work with other programs that depend on dnsmasq.

**[BUG | ISSUE] Actual Behaviour:**
in virt-manager when I try to start network I get this popup with error:
```
Error starting network 'default': Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/network.py", line 75, in start
    self._backend.create()
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 3075, in create
    if ret == -1: raise libvirtError ('virNetworkCreate() failed', net=self)
libvirt.libvirtError: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
```

also the `libvirtd` daemon complains about missing `dnsmasq`
```
[deemon@Zen ~]$ systemctl status libvirtd
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; disabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-03-24 23:29:49 EET; 53min ago
TriggeredBy: ● libvirtd-ro.socket
             ● libvirtd-admin.socket
             ● libvirtd.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
   Main PID: 20101 (libvirtd)
      Tasks: 17 (limit: 32768)
     Memory: 94.1M
     CGroup: /system.slice/libvirtd.service
             └─20101 /usr/bin/libvirtd

märts 24 23:29:49 Zen libvirtd[20101]: Libvirt doesn't support VirtualBox API version 6001004
märts 24 23:29:49 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 24 23:30:20 Zen libvirtd[20101]: operation failed: pool 'default' already exists with uuid 2dde3efa-8d77-4c5c-b52c-40939f2b23c7
märts 24 23:30:29 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 24 23:31:57 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 24 23:32:21 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 24 23:44:53 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 25 00:13:38 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 25 00:16:24 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
märts 25 00:16:32 Zen libvirtd[20101]: Cannot check dnsmasq binary /usr/bin/dnsmasq: No such file or directory
```

**[BUG | ISSUE] Steps to reproduce:**
- install pi-hole-ftl
- let it replace existing dnsmasq
- observe virt-manager not working anymore and complaining about not existing networks due to missing dnsmasq
-

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: PC
OS:
```
uname -a
Linux Zen 5.5.11-1-MANJARO #1 SMP PREEMPT Sat Mar 21 16:54:29 UTC 2020 x86_64 GNU/Linux
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
You'd have a better solution to ask libvirt to not depend on an absolute binary name and path.

**Comment by dschaper** [comment]
And for information: https://docs.pi-hole.net/main/prerequesites/
